name: personal_scheduled_action_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.12.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.0
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0